name: Build and Push to Nexus

on:
  push:
    branches:
      - "**"   # startet bei jedem Branch
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t example-kube:latest .

      - name: Login to Nexus Docker Registry
        run: |
          echo "${{ secrets.NEXUS_PASSWORD }}" | docker login nexus.skyered-devops.de -u "${{ secrets.NEXUS_USERNAME }}" --password-stdin

      - name: Tag image for Nexus
        run: |
          docker tag example-kube:latest nexus.skyered-devops.de/example-kube:latest

      - name: Push image to Nexus
        run: |
          docker push nexus.skyered-devops.de/example-kube:latest
